//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMoveWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderImage
    {
        public int ImageId { get; set; }

        [Required]
        public int OrderId { get; set; }

        [Required]
        public string ImageURL { get; set; }

        public virtual Order Order { get; set; }
    }
}
