//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMoveWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.CustomerRatings = new HashSet<CustomerRating>();
            this.OrderBids = new HashSet<OrderBid>();
            this.OrderImages = new HashSet<OrderImage>();
            this.OrderPayments = new HashSet<OrderPayment>();
            this.TruckOwnerRatings = new HashSet<TruckOwnerRating>();
        }
    
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public int TruckTypeId { get; set; }
        public System.DateTime OrderDateTime { get; set; }
        public string PickupPlace { get; set; }
        public double PickupLat { get; set; }
        public double PickupLong { get; set; }
        public string PickupUnitNumber { get; set; }
        public int PickupFloor { get; set; }
        public bool PickupHasElevator { get; set; }
        public string PickupDistanceFromParking { get; set; }
        public string PickupAdditionalInfo { get; set; }
        public string DropPlace { get; set; }
        public double DropLat { get; set; }
        public double DropLong { get; set; }
        public string DropUnitNumber { get; set; }
        public int DropFloor { get; set; }
        public bool DropHasElevator { get; set; }
        public string DropDistanceFromParking { get; set; }
        public string DropAdditionalInfo { get; set; }
        public Nullable<int> EstimatedNumOfTrips { get; set; }
        public string EstimatedWeight { get; set; }
        public string EstimatedArea { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string OrderStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRating> CustomerRatings { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBid> OrderBids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderImage> OrderImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPayment> OrderPayments { get; set; }
        public virtual TruckType TruckType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckOwnerRating> TruckOwnerRatings { get; set; }
    }
}
