//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMoveWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public int PaymentId { get; set; }
        public int OrderId { get; set; }
        public int CustomerCCId { get; set; }
        public double PaymentAmout { get; set; }
        public string PaymentType { get; set; }
        public string PaymentStatus { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual CustomerCreditCard CustomerCreditCard { get; set; }
        public virtual Order Order { get; set; }
    }
}
