//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMoveWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderBid
    {
        public int BidId { get; set; }

        [Required]
        public int OrderId { get; set; }

        [Required]
        public int TruckOwnerId { get; set; }

        [Required]
        public System.DateTime DeliveryStartTime { get; set; }

        [Required]
        public double NumberOfHours { get; set; }

        [Required]
        public int NumberOfTrips { get; set; }

        [Required]
        public double BidAmount { get; set; }

        [Required]
        [StringLength(50)]
        public string BidStatus { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual TruckOwner TruckOwner { get; set; }
    }
}
