//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMoveWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckOwnerRating
    {
        public int RatingId { get; set; }
        public int TruckOwnerId { get; set; }
        public int OrderId { get; set; }
        public int Rating { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual TruckOwner TruckOwner { get; set; }
    }
}
