//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMoveWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TruckOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TruckOwner()
        {
            this.OrderBids = new HashSet<OrderBid>();
            this.TruckOwnerCreditCards = new HashSet<TruckOwnerCreditCard>();
            this.TruckOwnerRatings = new HashSet<TruckOwnerRating>();
        }
    
        public int TruckOwnerId { get; set; }

        public int TruckId { get; set; }

        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        public string LastName { get; set; }

        [Required]
        [StringLength(50)]
        public string Phone { get; set; }

        [Required]
        [StringLength(50)]
        public string Email { get; set; }

        public string Address1 { get; set; }
        public string Address2 { get; set; }

        [StringLength(50)]
        public string ZipCode { get; set; }

        [StringLength(50)]
        public string City { get; set; }

        [StringLength(50)]
        public string State { get; set; }

        public string ProfilePictureURL { get; set; }
        public string DriverLicensePicURL { get; set; }
        public string VehicleRegPicURL { get; set; }
        public string DriverInsurancePicURL { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBid> OrderBids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckOwnerCreditCard> TruckOwnerCreditCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckOwnerRating> TruckOwnerRatings { get; set; }
        public virtual Truck Truck { get; set; }
    }
}
