//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMoveWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        public int TruckId { get; set; }
        public int TruckOwnerId { get; set; }
        public int TruckTypeId { get; set; }
        public string TruckMake { get; set; }
        public string TruckModel { get; set; }
        public string TruckYear { get; set; }
        public string LicensePlate { get; set; }
        public string TruckColor { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    
        public virtual TruckType TruckType { get; set; }
        public virtual TruckOwner TruckOwner { get; set; }
    }
}
