//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMoveWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Truck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truck()
        {
            this.TruckOwners = new HashSet<TruckOwner>();
        }
    
        public int TruckId { get; set; }

        [Required]
        public int TruckTypeId { get; set; }

        [Required]
        [StringLength(50)]
        public string TruckMake { get; set; }

        [Required]
        [StringLength(50)]
        public string TruckModel { get; set; }

        [Required]
        [StringLength(50)]
        public string TruckYear { get; set; }

        [Required]
        [StringLength(50)]
        public string LicensePlate { get; set; }

        [Required]
        [StringLength(50)]
        public string TruckColor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckOwner> TruckOwners { get; set; }
        public virtual TruckType TruckType { get; set; }
    }
}
