//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMoveWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TruckOwnerCreditCard
    {
        public int CCId { get; set; }

        [Required]
        public int TruckOwnerId { get; set; }

        [Required]
        [StringLength(50)]
        public string CCNumber { get; set; }

        [Required]
        [StringLength(100)]
        public string CCName { get; set; }

        [Required]
        [StringLength(50)]
        public string CCType { get; set; }

        [Required]
        public int CCCRVNumber { get; set; }

        [Required]
        public int CCExpiryMonth { get; set; }

        [Required]
        public int CCExpiryYear { get; set; }

        public string CCZipCode { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual TruckOwner TruckOwner { get; set; }
    }
}
